name = 'Thenral Hugo'
license = 'MIT'
licenselink = 'https://github.com/studiolampblack/thenral-hugo/blob/main/LICENSE'
description = 'Thenral Hugo : A minimalist Hugo theme built with TailwindCSS, for efficient performance and minimalism'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/studiolampblack/thenral-hugo'

# If you have a running demo of the theme
demosite = 'https://millennierd.com/'

# Taxonomy terms
tags = ['blog', 'responsive', 'light', 'tailwindcss']
features = ['tailwindcss', 'two-column', 'sidebar', 'horizontal-menu']

# If the theme has multiple authors

[author]
  name = 'Ram Iyer'
  homepage = 'https://ramiyer.io/'
